version: '3.8'

services:
  backend:
    container_name: node-backend
    build:
      context: ./api
      dockerfile: Dockerfile
    image: node-backend:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL_PRISMA}
    depends_on:
      - db
    volumes:
      - ./api:/app

  frontend:
    container_name: react-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    image: react-frontend:latest
    ports:
      - 3000:3000
    volumes:
      - ./front:/app

  db:
    container_name: postgres-sql
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
